#TODO DB Setup
#TODO ENV filling
services:
  server:
    container_name: d2d_server
    build: ./server
    ports:
      - "5555:5555"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5555
      - DATABASE_URL=postgresql://postgres:postgres@pg:5432/d2d
    depends_on:
      - pg

  client:
    container_name: d2d_client
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  pg:
    container_name: d2d_pg
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: d2d
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    container_name: d2d_valkey
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: ["valkey-server", "--requirepass", "valkeypassword"]

  mongo:
    container_name: d2d_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data: {}
  valkey_data: {}
  mongo_data: {}
