version: "3.8"
#TODO DB Setup
#TODO ENV filling
services:
  server:
    build: ./server
    ports:
      - "5555:5555"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
    #depends_on: #when doing db

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - server
